### ISSUE TITLE
Changes in the documentation file

### ISSUE THREAD

**Issue by eleallegue** [Arquisoft/Loader_i3a#17]
Changes regarding the quality attributes, and some other parts of the document

**Comment by cristinavn** [comment]
Changes un the documentation regarding first deliverable:

    * Added 6 new quality scenarios and modified some others to include all constraints in the scenarios as quality attributes affected.
    * Added table rationale in Context View justifying why the view solves some quality attributes.
    * Modified Loader and Agents' rationale also.
    * Views table modified to include all quality attributes and architecture constraints.
