### ISSUE TITLE
Store also the password in the db

### ISSUE THREAD

**Issue by thewilly** [Arquisoft/Loader_i3a#2]
You should store also the password in the database, encrypted or plain but store it so we can find it later at the login.

https://github.com/Arquisoft/Loader_i3a/blob/7d0555cc349632d4c69f06c783b46826f08b2852/src/main/java/es/uniovi/asw/database/CitizenDaoImplMongo.java#L100-L118

**Comment by thewilly** [comment]
Closed by requierement of the team

**Comment by eleallegue** [comment]
The code has been changed, and the password field of the Agent is now added to the database.

**Comment by thewilly** [comment]
Perfect, thanks!
