### ISSUE TITLE
Add: update the views(section 9) adding the one relative to the incident management

### ISSUE THREAD

**Issue by UO251547** [Arquisoft/Loader_i3a#28]
Update section 9 form the documentation including  the new view given in module 3

**Comment by cristinavn** [comment]
All quality scenarios should be included in the views, as well as the affected quality attributes. 
New diagrams should also be included.
Small definition of the elements used in the component diagram of the InciManager module.
Table with the justification of why that scenario covers the quality attribute in the rationale part.

**Comment by alvarezGarciaMarcos** [comment]
Add the missing rationale part in the InciManager view.

**Comment by UO251547** [comment]
The rational part in the inciManager correspond to part 9.4.4 from the Documentation. I have already added it.
