### ISSUE TITLE
Problem: where to read the master.csv in the code

### ISSUE THREAD

**Issue by eleallegue** [Arquisoft/Loader_i3a#7]
Once we have the master.csv with the relationships of the kindCodes with the kind name, we have some constructors in the Agent.java:
```private int kindCode;
	private String kind;

	public Agent(String name, String location, String email, String ID, int kind) {

		this.name = name;
		setLocation(location);
		this.email = email;
		this.ID = ID;
		this.kindCode = kind;
	}

	public Agent(String name, String location, String email, String ID, int kind,String pass) {

		this(name,location,email,ID,kind);
		this.password = pass;
	}

	public Agent(String name, String email, String ID, int kind) {

		this.name = name;
		setLocation(null);// no location
		this.email = email;
		this.ID = ID;
		this.kindCode = kind;
	}

	public Agent(String[] data) {
		this.name = data[0];
		this.email = data[2];
		setLocation(data[1]);
		this.ID = data[3];
		Double k = Double.parseDouble(data[4]);
		this.kindCode = k.intValue();

	}```
It could be logic to add another parameter to the constructors, but the thing is that the last one (the one having as parameter an array of strings) is the one that obtains the information of the txt or the xls, so the thing is that I don't know what would be the best approach for getting the kind name in the code.

**Comment by thewilly** [comment]
Hi @eleallegue.
Best way, in my opinion is to resolve the kind from the kindcode at execution time, that is a new method called `getKind` or whatever you like that returns the String that contains the kind description (Person for example). 

In this way you're able to resolve properly your kindCode -> kind relation at any times. Imagine the following example.
```java
// From your first constructor for a person constructor.
// Name, Location, Email, ID, KindCode, Kind.
Agent paco = new Agent("Paco", "10N10W", "paco@uniovi.es", "11401223O", 1, "Person");

System.out.println(paco.getKindCode()+":"+paco.getKind()); // Will print -> 1:person
...
// The csv file changes and now 1 means university.
...
System.out.println(paco.getKindCode()+":"+paco.getKind()); // Will print -> 1:person but in the csv 1:university
```
Thats why the string of the kind `Person, Entity, Sensor...` should not be stored as a property in the Agent type.

**Comment by eleallegue** [comment]
That was my first thought, thank you!

**Comment by eleallegue** [comment]
I will use the code you showed me in another issue, but, what library did you use for makinf this code work? and how do you introduce the dependency of that library to maven and pom.xml?
```public String getKind() {
	    try {
	        return CSVFile.of( new URL( "src/main/resources/master.csv" ), ",", "id", "kind" )
		    .getRows().stream()
		    .filter( r -> r.getColumn( "id" ).equals( Integer.toString( kindCode ) ) )
		    .findAny().get().getColumn( "kind" );
	    } catch (NoSuchElementException e) {
	        return KIND_NOT_FOUND;
	    }
	} ```

**Comment by thewilly** [comment]
Nice, the library we used is called [Swift](https://github.com/computer-engineering-uniovi/swift). And for adding the dependency to the pom.xml you can use its [jitpack](https://jitpack.io/#computer-engineering-uniovi/swift/1.1.1-candidate) website. You will have to copy and paste the repository dependency and the library one. It's really well explained there, but anyway, ask for anything!

**Comment by thewilly** [comment]
To import the swift dependencies you will have to update your pom.xml file.
https://github.com/Arquisoft/Loader_i3a/blob/a1de452b2648daa98b4e814662841d3075a36edf/pom.xml#L16-L107
After line 106 insert the following code:
```xml
<dependency>
    <groupId>com.github.computer-engineering-uniovi</groupId>
    <artifactId>swift</artifactId>
    <version>1.1.1-candidate</version>
</dependency>
```

And then after line 290 https://github.com/Arquisoft/Loader_i3a/blob/a1de452b2648daa98b4e814662841d3075a36edf/pom.xml#L290 insert this code:
```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```

**Comment by eleallegue** [comment]
Yes! Perfect! Thank you very much! 💯
